# Memberikan perintah bahwa schema version yang digunakan adalah 3.7
version: "3.7"

# Menambahkan services yang akan dijalankan
services:

# menambahkan service kedua, yang berupa item-app
  item-app:

    depends_on: 
      item-db:
        condition: service_started

# menggunakan image yang sudah dideploy
    image: fikro12/item-app:v1

# memberikan opsi untuk selalu restart ketika terjadi error
    restart: always

# mempetakan port agar dapat diakses dari port 80
    ports:
      - 80:3000

    
# menambahkan service kedua, yang berupa item-db
  item-db:
# memberikan image mongo:3
    image: mongo:3
# memberikan kesempatan untuk restart ketika diperlukan
    restart: always
# mengature volume agar menggunakan app-db:/data/db
    volumes:
      - app-db:/data/db

    
# Menggunakan volumes custom name

volumes:

# memberinama custom volume dengan nama app-db
  app-db:

